import type { Agent } from "@/lib/types";

// ============================================================================
// FLOW — Mock Agent Pool (10 reusable agents)
// ============================================================================

export const agents: Record<string, Agent> = {
  athena: {
    id: "agent-planner",
    name: "Athena",
    role: "planner",
    status: "completed",
    avatar: "AT",
    model: "claude-opus-4-6",
    currentAction: null,
    actions: [],
    tokensUsed: 45200,
    costUsd: 2.15,
  },
  blueprint: {
    id: "agent-architect",
    name: "Blueprint",
    role: "architect",
    status: "thinking",
    avatar: "BP",
    model: "claude-opus-4-6",
    currentAction: "Designing database schema for user permissions module",
    actions: [
      {
        id: "act-1",
        timestamp: "2026-04-03T09:15:00Z",
        type: "research",
        description: "Analyzing existing auth patterns in codebase",
        status: "completed",
        durationMs: 12400,
        output: "Found 3 auth middleware files, 2 role-based access patterns. Recommending RBAC with attribute-based extensions.",
        requiresApproval: false,
        approvedBy: null,
      },
      {
        id: "act-2",
        timestamp: "2026-04-03T09:16:30Z",
        type: "plan",
        description: "Designing database schema for user permissions module",
        status: "executing",
        durationMs: null,
        output: null,
        requiresApproval: true,
        approvedBy: null,
      },
    ],
    tokensUsed: 128750,
    costUsd: 6.44,
  },
  forge: {
    id: "agent-dev",
    name: "Flow",
    role: "developer",
    status: "executing",
    avatar: "FG",
    model: "claude-sonnet-4-6",
    currentAction: "Implementing OAuth2 callback handler",
    actions: [
      {
        id: "act-3",
        timestamp: "2026-04-03T08:45:00Z",
        type: "code",
        description: "Implementing OAuth2 callback handler",
        status: "executing",
        durationMs: null,
        output: null,
        requiresApproval: false,
        approvedBy: null,
      },
    ],
    tokensUsed: 89300,
    costUsd: 1.34,
  },
  sentinel: {
    id: "agent-tester",
    name: "Sentinel",
    role: "tester",
    status: "idle",
    avatar: "SN",
    model: "claude-sonnet-4-6",
    currentAction: null,
    actions: [],
    tokensUsed: 0,
    costUsd: 0,
  },
  oracle: {
    id: "agent-reviewer",
    name: "Oracle",
    role: "reviewer",
    status: "awaiting_approval",
    avatar: "OR",
    model: "claude-opus-4-6",
    currentAction: "Security review flagged: SQL injection risk in query builder",
    actions: [
      {
        id: "act-4",
        timestamp: "2026-04-03T08:30:00Z",
        type: "review",
        description: "Security review of query builder module",
        status: "awaiting_approval",
        durationMs: 8200,
        output: "CRITICAL: Raw string interpolation detected in buildQuery(). Recommend parameterized queries. Blocking merge until resolved.",
        requiresApproval: true,
        approvedBy: null,
      },
    ],
    tokensUsed: 34100,
    costUsd: 1.62,
  },
  nexus: {
    id: "agent-deployer",
    name: "Nexus",
    role: "deployer",
    status: "idle",
    avatar: "NX",
    model: "claude-sonnet-4-6",
    currentAction: null,
    actions: [],
    tokensUsed: 12400,
    costUsd: 0.19,
  },
  cipher: {
    id: "agent-security",
    name: "Cipher",
    role: "reviewer",
    status: "executing",
    avatar: "CP",
    model: "claude-opus-4-6",
    currentAction: "Running static analysis on payment gateway module",
    actions: [
      {
        id: "act-5",
        timestamp: "2026-04-04T07:20:00Z",
        type: "review",
        description: "Static analysis on payment gateway module",
        status: "executing",
        durationMs: null,
        output: null,
        requiresApproval: false,
        approvedBy: null,
      },
    ],
    tokensUsed: 67800,
    costUsd: 3.22,
  },
  spark: {
    id: "agent-dev2",
    name: "Spark",
    role: "developer",
    status: "thinking",
    avatar: "SP",
    model: "claude-sonnet-4-6",
    currentAction: "Analyzing ETL pipeline bottleneck in transformation layer",
    actions: [
      {
        id: "act-6",
        timestamp: "2026-04-04T06:50:00Z",
        type: "research",
        description: "Profiling ETL transformation performance",
        status: "executing",
        durationMs: null,
        output: null,
        requiresApproval: false,
        approvedBy: null,
      },
    ],
    tokensUsed: 54200,
    costUsd: 0.81,
  },
  atlas: {
    id: "agent-architect2",
    name: "Atlas",
    role: "architect",
    status: "completed",
    avatar: "AL",
    model: "claude-opus-4-6",
    currentAction: null,
    actions: [],
    tokensUsed: 98400,
    costUsd: 4.68,
  },
  prism: {
    id: "agent-tester2",
    name: "Prism",
    role: "tester",
    status: "executing",
    avatar: "PM",
    model: "claude-sonnet-4-6",
    currentAction: "Running accessibility audit on portal components",
    actions: [
      {
        id: "act-7",
        timestamp: "2026-04-04T08:10:00Z",
        type: "test",
        description: "WCAG 2.2 AA compliance audit",
        status: "executing",
        durationMs: null,
        output: null,
        requiresApproval: false,
        approvedBy: null,
      },
    ],
    tokensUsed: 41600,
    costUsd: 0.62,
  },
};

export const agentList: Agent[] = Object.values(agents);
