import type { FlowTemplate } from "@/lib/types";

// ============================================================================
// Flow Templates — The character roster for launching AI workflows
// Each template spawns bespoke agents to execute the workflow
// ============================================================================

export interface FlowCategoryMeta {
  key: string;
  label: string;
  description: string;
  icon: string;
  color: string;
  gradient: string;
  flowCount?: number;
}

export const FLOW_CATEGORIES: FlowCategoryMeta[] = [
  {
    key: "engineering",
    label: "Engineering",
    description: "Build, test, and ship production-grade software with AI agents that architect, code, review, and deploy.",
    icon: "Code",
    color: "#8b5cf6",
    gradient: "from-violet-600/25 via-violet-500/5 to-transparent",
  },
  {
    key: "security",
    label: "Security",
    description: "Protect your codebase with automated vulnerability scanning, penetration testing, and compliance frameworks.",
    icon: "Shield",
    color: "#ef4444",
    gradient: "from-red-600/25 via-red-500/5 to-transparent",
  },
  {
    key: "infrastructure",
    label: "Infrastructure",
    description: "Architect cloud systems, configure CI/CD pipelines, and automate incident response at scale.",
    icon: "Cloud",
    color: "#3b82f6",
    gradient: "from-blue-600/25 via-blue-500/5 to-transparent",
  },
  {
    key: "data",
    label: "Data & AI",
    description: "Design data pipelines, train ML models, and generate competitive intelligence from any data source.",
    icon: "Brain",
    color: "#ec4899",
    gradient: "from-pink-600/25 via-pink-500/5 to-transparent",
  },
  {
    key: "product",
    label: "Product",
    description: "Design systems, orchestrate launches, and automate documentation — from concept to customer.",
    icon: "Rocket",
    color: "#f97316",
    gradient: "from-orange-600/25 via-orange-500/5 to-transparent",
  },
  {
    key: "operations",
    label: "Operations",
    description: "Automate support, content, finance, and people operations with specialised AI workflows.",
    icon: "Users",
    color: "#10b981",
    gradient: "from-emerald-600/25 via-emerald-500/5 to-transparent",
  },
];

export const flowTemplates: FlowTemplate[] = [
  // ── Engineering ──────────────────────────────────────────────
  {
    id: "flow-fullstack",
    name: "Full-Stack Build",
    tagline: "Architect, build, and ship production code",
    description: "End-to-end software development workflow. AI agents handle architecture decisions, code generation, testing, code review, and deployment. From feature request to production in record time.",
    category: "engineering",
    icon: "Code",
    color: "#8b5cf6",
    gradient: "from-violet-600/20 via-violet-500/5 to-transparent",
    agents: [
      { name: "Athena", role: "Architect", description: "Designs system architecture and breaks work into epics" },
      { name: "Nova", role: "Developer", description: "Writes production-grade code across the stack" },
      { name: "Sentinel", role: "Reviewer", description: "Reviews code for quality, security, and best practices" },
      { name: "Phoenix", role: "Tester", description: "Generates and runs comprehensive test suites" },
    ],
    tags: ["frontend", "backend", "fullstack", "api"],
    estimatedSprints: 3,
    complexity: "standard",
  },
  {
    id: "flow-bughunt",
    name: "Bug Hunt",
    tagline: "Track, isolate, and eliminate defects",
    description: "Systematic bug triage and resolution workflow. AI agents reproduce bugs, isolate root causes, write fixes, and verify no regressions. Turns your bug backlog into a clean slate.",
    category: "engineering",
    icon: "Bug",
    color: "#ef4444",
    gradient: "from-red-600/20 via-red-500/5 to-transparent",
    agents: [
      { name: "Tracker", role: "Triage", description: "Categorizes, deduplicates, and prioritizes incoming bugs" },
      { name: "Probe", role: "Investigator", description: "Reproduces issues and isolates root causes" },
      { name: "Patch", role: "Developer", description: "Writes targeted fixes with regression tests" },
    ],
    tags: ["debugging", "qa", "triage", "testing"],
    estimatedSprints: 1,
    complexity: "starter",
  },
  {
    id: "flow-api",
    name: "API Forge",
    tagline: "Design, build, and integrate APIs at scale",
    description: "Complete API development lifecycle. Agents design OpenAPI specs, generate type-safe endpoints, write integration tests, build documentation, and set up monitoring. RESTful or GraphQL.",
    category: "engineering",
    icon: "Plug",
    color: "#f59e0b",
    gradient: "from-amber-600/20 via-amber-500/5 to-transparent",
    agents: [
      { name: "Blueprint", role: "API Designer", description: "Creates OpenAPI/GraphQL schemas from requirements" },
      { name: "Forge", role: "Developer", description: "Implements endpoints with validation and error handling" },
      { name: "Postman", role: "Tester", description: "Generates integration and contract tests" },
      { name: "Scribe", role: "Documenter", description: "Writes API docs with examples and SDKs" },
    ],
    tags: ["rest", "graphql", "openapi", "integration"],
    estimatedSprints: 2,
    complexity: "standard",
  },
  {
    id: "flow-migration",
    name: "Database Migration",
    tagline: "Migrate schemas and data with zero downtime",
    description: "Safe database migration workflow with rollback planning. Agents analyze existing schemas, generate migration scripts, validate data integrity, and execute with zero-downtime strategies.",
    category: "engineering",
    icon: "Database",
    color: "#06b6d4",
    gradient: "from-cyan-600/20 via-cyan-500/5 to-transparent",
    agents: [
      { name: "Mapper", role: "Schema Analyst", description: "Maps source to target schemas with diff analysis" },
      { name: "Migrator", role: "Migration Engineer", description: "Generates idempotent migration scripts" },
      { name: "Validator", role: "Data Integrity", description: "Validates data consistency post-migration" },
    ],
    tags: ["database", "migration", "schema", "data"],
    estimatedSprints: 2,
    complexity: "advanced",
  },
  {
    id: "flow-refactor",
    name: "Code Refactor",
    tagline: "Modernize legacy code without breaking changes",
    description: "Systematic refactoring workflow. Agents analyze code quality metrics, identify refactoring opportunities, execute changes incrementally, and ensure all tests pass at every step.",
    category: "engineering",
    icon: "RefreshCw",
    color: "#a78bfa",
    gradient: "from-violet-400/20 via-violet-300/5 to-transparent",
    agents: [
      { name: "Analyst", role: "Code Auditor", description: "Identifies tech debt, complexity hotspots, and patterns" },
      { name: "Surgeon", role: "Refactor Engineer", description: "Executes targeted refactors with zero regressions" },
      { name: "Guardian", role: "Test Shield", description: "Ensures test coverage is maintained throughout" },
    ],
    tags: ["refactoring", "tech-debt", "modernization", "quality"],
    estimatedSprints: 2,
    complexity: "standard",
  },

  // ── Security ─────────────────────────────────────────────────
  {
    id: "flow-security",
    name: "Security Audit",
    tagline: "Penetration testing and vulnerability scanning",
    description: "Comprehensive security assessment workflow. Agents perform SAST/DAST scanning, dependency auditing, secret detection, and generate remediation plans ranked by severity and exploitability.",
    category: "security",
    icon: "Shield",
    color: "#dc2626",
    gradient: "from-red-700/20 via-red-600/5 to-transparent",
    agents: [
      { name: "Scanner", role: "Vulnerability Analyst", description: "Runs SAST, DAST, and dependency scans" },
      { name: "Hunter", role: "Pen Tester", description: "Identifies attack vectors and exploit chains" },
      { name: "Remediate", role: "Fix Engineer", description: "Patches vulnerabilities with minimal blast radius" },
      { name: "Auditor", role: "Compliance", description: "Generates audit reports and evidence packages" },
    ],
    tags: ["security", "pentest", "vulnerability", "audit"],
    estimatedSprints: 1,
    complexity: "advanced",
  },
  {
    id: "flow-compliance",
    name: "Compliance Shield",
    tagline: "SOC2, GDPR, PCI compliance automation",
    description: "Automated compliance workflow. Agents map your codebase against compliance frameworks, identify gaps, implement controls, generate evidence, and maintain continuous compliance monitoring.",
    category: "security",
    icon: "Lock",
    color: "#d97706",
    gradient: "from-amber-700/20 via-amber-600/5 to-transparent",
    agents: [
      { name: "Mapper", role: "Control Mapper", description: "Maps codebase against compliance frameworks" },
      { name: "Implementer", role: "Control Engineer", description: "Implements missing controls and policies" },
      { name: "Evidence", role: "Auditor", description: "Collects and packages audit evidence automatically" },
    ],
    tags: ["soc2", "gdpr", "pci", "hipaa", "compliance"],
    estimatedSprints: 3,
    complexity: "enterprise",
  },

  // ── Infrastructure ───────────────────────────────────────────
  {
    id: "flow-cloud",
    name: "Cloud Architect",
    tagline: "Infrastructure as code with auto-scaling",
    description: "Cloud infrastructure workflow. Agents design architecture, write Terraform/Pulumi, configure networking, set up monitoring, and implement auto-scaling — across AWS, GCP, or Azure.",
    category: "infrastructure",
    icon: "Cloud",
    color: "#3b82f6",
    gradient: "from-blue-600/20 via-blue-500/5 to-transparent",
    agents: [
      { name: "Architect", role: "Cloud Designer", description: "Designs resilient, cost-optimized cloud architecture" },
      { name: "Terraform", role: "IaC Engineer", description: "Writes infrastructure as code with state management" },
      { name: "Monitor", role: "Observability", description: "Sets up monitoring, alerting, and dashboards" },
    ],
    tags: ["aws", "gcp", "azure", "terraform", "kubernetes"],
    estimatedSprints: 3,
    complexity: "advanced",
  },
  {
    id: "flow-cicd",
    name: "CI/CD Pipeline",
    tagline: "Build, test, and deploy with confidence",
    description: "Complete CI/CD setup workflow. Agents configure build pipelines, test automation, staging environments, blue-green deployments, and rollback strategies. Ship faster with zero fear.",
    category: "infrastructure",
    icon: "GitBranch",
    color: "#22c55e",
    gradient: "from-green-600/20 via-green-500/5 to-transparent",
    agents: [
      { name: "Pipeline", role: "CI Engineer", description: "Configures build, lint, and test pipelines" },
      { name: "Deploy", role: "CD Engineer", description: "Sets up deployment strategies and rollback" },
      { name: "Gate", role: "Quality Gate", description: "Enforces quality gates and approval workflows" },
    ],
    tags: ["ci", "cd", "github-actions", "deployment", "devops"],
    estimatedSprints: 1,
    complexity: "standard",
  },
  {
    id: "flow-incident",
    name: "Incident Response",
    tagline: "Detect, triage, and resolve incidents fast",
    description: "Automated incident management workflow. Agents detect anomalies, create incident channels, coordinate response, write post-mortems, and implement preventive measures.",
    category: "infrastructure",
    icon: "AlertTriangle",
    color: "#ef4444",
    gradient: "from-red-500/20 via-red-400/5 to-transparent",
    agents: [
      { name: "Watchdog", role: "Detection", description: "Monitors systems and detects anomalies in real-time" },
      { name: "Commander", role: "Incident Lead", description: "Coordinates response and assigns tasks" },
      { name: "Analyst", role: "Root Cause", description: "Investigates root cause and writes post-mortems" },
    ],
    tags: ["incident", "monitoring", "sre", "on-call"],
    estimatedSprints: 2,
    complexity: "advanced",
  },

  // ── Data & AI ────────────────────────────────────────────────
  {
    id: "flow-datapipeline",
    name: "Data Pipeline",
    tagline: "ETL, streaming, and warehouse orchestration",
    description: "End-to-end data engineering workflow. Agents design data models, build ETL/ELT pipelines, configure streaming, validate data quality, and optimize query performance.",
    category: "data",
    icon: "BarChart3",
    color: "#06b6d4",
    gradient: "from-cyan-500/20 via-cyan-400/5 to-transparent",
    agents: [
      { name: "Modeler", role: "Data Architect", description: "Designs dimensional models and data contracts" },
      { name: "Plumber", role: "Pipeline Engineer", description: "Builds ETL/ELT with Spark, dbt, or Airflow" },
      { name: "Quality", role: "Data Quality", description: "Implements data validation and monitoring" },
    ],
    tags: ["etl", "streaming", "warehouse", "analytics"],
    estimatedSprints: 3,
    complexity: "advanced",
  },
  {
    id: "flow-mlops",
    name: "AI Model Ops",
    tagline: "Train, evaluate, and deploy ML models",
    description: "Machine learning operations workflow. Agents manage data preparation, model training, evaluation, A/B testing, and production serving with drift monitoring and retraining pipelines.",
    category: "data",
    icon: "Brain",
    color: "#ec4899",
    gradient: "from-pink-600/20 via-pink-500/5 to-transparent",
    agents: [
      { name: "Trainer", role: "ML Engineer", description: "Trains and fine-tunes models with hyperparameter optimization" },
      { name: "Evaluator", role: "Model Analyst", description: "Runs evaluation suites and bias detection" },
      { name: "Deployer", role: "MLOps", description: "Deploys models with canary rollout and monitoring" },
    ],
    tags: ["machine-learning", "mlops", "training", "inference"],
    estimatedSprints: 4,
    complexity: "enterprise",
  },
  {
    id: "flow-research",
    name: "Research Intel",
    tagline: "Competitive intelligence and market research",
    description: "Strategic research workflow. Agents gather market data, analyze competitors, identify trends, synthesize findings, and produce executive-ready intelligence reports.",
    category: "data",
    icon: "Search",
    color: "#6366f1",
    gradient: "from-indigo-600/20 via-indigo-500/5 to-transparent",
    agents: [
      { name: "Scout", role: "Researcher", description: "Gathers data from multiple sources and APIs" },
      { name: "Analyst", role: "Intelligence", description: "Synthesizes findings into actionable insights" },
      { name: "Reporter", role: "Writer", description: "Produces executive briefs and detailed reports" },
    ],
    tags: ["research", "competitive", "market", "intelligence"],
    estimatedSprints: 1,
    complexity: "starter",
  },

  // ── Product ──────────────────────────────────────────────────
  {
    id: "flow-designsystem",
    name: "Design System",
    tagline: "Build pixel-perfect component libraries",
    description: "Design system creation workflow. Agents audit existing UI, define design tokens, build accessible components, create documentation, and set up visual regression testing.",
    category: "product",
    icon: "Palette",
    color: "#10b981",
    gradient: "from-emerald-600/20 via-emerald-500/5 to-transparent",
    agents: [
      { name: "Auditor", role: "UI Analyst", description: "Audits existing components and identifies patterns" },
      { name: "Builder", role: "Component Dev", description: "Creates accessible, themeable components" },
      { name: "Documenter", role: "Design Docs", description: "Writes Storybook stories and usage guidelines" },
    ],
    tags: ["design", "components", "accessibility", "tokens"],
    estimatedSprints: 3,
    complexity: "standard",
  },
  {
    id: "flow-launch",
    name: "Product Launch",
    tagline: "Go-to-market execution from A to Z",
    description: "Product launch orchestration. Agents coordinate feature completion, QA sign-off, marketing assets, documentation, release notes, and deployment with rollback contingency.",
    category: "product",
    icon: "Rocket",
    color: "#f97316",
    gradient: "from-orange-600/20 via-orange-500/5 to-transparent",
    agents: [
      { name: "Coordinator", role: "Launch Lead", description: "Orchestrates all launch activities and dependencies" },
      { name: "QA Lead", role: "Quality Gate", description: "Ensures all acceptance criteria are met" },
      { name: "Comms", role: "Release Comms", description: "Writes release notes, docs, and announcements" },
    ],
    tags: ["launch", "release", "go-to-market", "coordination"],
    estimatedSprints: 1,
    complexity: "standard",
  },
  {
    id: "flow-docs",
    name: "Doc Smith",
    tagline: "Documentation and knowledge base generation",
    description: "Automated documentation workflow. Agents analyze codebases, generate API docs, write guides, create architecture diagrams, and build searchable knowledge bases.",
    category: "product",
    icon: "BookOpen",
    color: "#14b8a6",
    gradient: "from-teal-600/20 via-teal-500/5 to-transparent",
    agents: [
      { name: "Analyzer", role: "Code Reader", description: "Parses codebases and extracts documentation needs" },
      { name: "Writer", role: "Tech Writer", description: "Writes clear, structured documentation" },
      { name: "Organizer", role: "Knowledge Architect", description: "Structures and cross-links documentation" },
    ],
    tags: ["documentation", "api-docs", "knowledge-base", "guides"],
    estimatedSprints: 1,
    complexity: "starter",
  },

  // ── Operations ───────────────────────────────────────────────
  {
    id: "flow-support",
    name: "Support Ops",
    tagline: "AI-powered customer support automation",
    description: "Customer support workflow. Agents classify tickets, suggest resolutions, draft responses, escalate complex issues, and build a self-improving knowledge base from resolved tickets.",
    category: "operations",
    icon: "Headphones",
    color: "#818cf8",
    gradient: "from-indigo-500/20 via-indigo-400/5 to-transparent",
    agents: [
      { name: "Classifier", role: "Triage", description: "Categorizes and routes incoming support tickets" },
      { name: "Resolver", role: "Support Agent", description: "Drafts responses using knowledge base and context" },
      { name: "Escalator", role: "Escalation", description: "Identifies and routes complex issues to humans" },
    ],
    tags: ["support", "ticketing", "customer", "helpdesk"],
    estimatedSprints: 2,
    complexity: "standard",
  },
  {
    id: "flow-content",
    name: "Content Engine",
    tagline: "Content creation, approval, and publishing",
    description: "Content operations workflow. Agents research topics, generate drafts, optimize for SEO, route through approval chains, and schedule publishing across channels.",
    category: "operations",
    icon: "FileText",
    color: "#2dd4bf",
    gradient: "from-teal-400/20 via-teal-300/5 to-transparent",
    agents: [
      { name: "Researcher", role: "Content Research", description: "Identifies topics, keywords, and content gaps" },
      { name: "Creator", role: "Writer", description: "Generates high-quality drafts with brand voice" },
      { name: "Publisher", role: "Distribution", description: "Optimizes and schedules across channels" },
    ],
    tags: ["content", "marketing", "seo", "publishing"],
    estimatedSprints: 2,
    complexity: "standard",
  },
  {
    id: "flow-financial",
    name: "Financial Ops",
    tagline: "Invoicing, reconciliation, and reporting",
    description: "Financial operations workflow. Agents process invoices, reconcile transactions, detect anomalies, generate reports, and maintain audit trails for financial compliance.",
    category: "operations",
    icon: "DollarSign",
    color: "#10b981",
    gradient: "from-emerald-500/20 via-emerald-400/5 to-transparent",
    agents: [
      { name: "Processor", role: "Invoice Agent", description: "Processes and validates incoming invoices" },
      { name: "Reconciler", role: "Reconciliation", description: "Matches transactions and flags discrepancies" },
      { name: "Reporter", role: "Financial Analyst", description: "Generates financial reports and forecasts" },
    ],
    tags: ["finance", "invoicing", "reconciliation", "reporting"],
    estimatedSprints: 2,
    complexity: "advanced",
  },
  {
    id: "flow-hr",
    name: "People Ops",
    tagline: "Onboarding, workflows, and team management",
    description: "HR automation workflow. Agents generate onboarding checklists, provision accounts, schedule training, collect feedback, and maintain compliance documentation.",
    category: "operations",
    icon: "Users",
    color: "#f43f5e",
    gradient: "from-rose-600/20 via-rose-500/5 to-transparent",
    agents: [
      { name: "Onboarder", role: "Onboarding Lead", description: "Generates personalized onboarding plans" },
      { name: "Provisioner", role: "Access Manager", description: "Provisions accounts and permissions" },
      { name: "Trainer", role: "Learning", description: "Creates and schedules training programs" },
    ],
    tags: ["hr", "onboarding", "people", "workforce"],
    estimatedSprints: 2,
    complexity: "standard",
  },
];
